comics/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from main import urls as mainURLS
from marvel import urls as marvelURLS

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^marvel/', include(marvelURLS,namespace="marv")),
    url(r'^', include(mainURLS,namespace="main")),
]

main/urls.py
from django.conf.urls import url
from . import views

urlpatterns=[
	url(r'^$',views.Home.as_view(),name="home")
]

marvel/urls.py
from django.conf.urls import url
from . import views

urlpatterns=[
	url(r'^$',views.Home.as_view(),name="home"),
	url(r'^historial/',views.Historial.as_view(),name="historial"),
]

main/models.py
from django.db import models

# Create your models here.

marvel/models.py
from django.db import models


class Heroe(models.Model):
	nombre=models.CharField(max_length=140)
	desc=models.TextField()
	img=models.CharField(max_length=500)

	def __str__(self):
		return self.nombre

main/views.py
from django.shortcuts import render
from django.views.generic import View

class Home(View):
	def get(self,request):
		return render(request,'main/home.html')

marvel/views.py
from django.shortcuts import render
from django.views.generic import View
from .mv import Marvel
from .models import Heroe

class Home(View):
	def get(self,request):
		template_name='marvel/home.html'
		historial = Heroe.objects.all()

		context={
			'historial':historial
		}
		return render(request,template_name,context)

	def post(self,request):
		heroe=request.POST.get('heroe')
		
		heroes = request.POST.getlist('heroe')
		
		if len(heroes)>1:
			if len(heroes[0])>0:
				heroe=heroes[0]
			else:
				heroe=heroes[1]

		mv=Marvel()
		personaje=mv.get_personaje(heroe)

		print(heroe)
		historial = Heroe.objects.all()


		
		link=mv.get_imagen()

		if len(personaje)==0:
			personaje="Sin descripcion"

		if len(link)>0:
			if Heroe.objects.filter(nombre=heroe).count()==0:
				heroeModel=Heroe.objects.create(nombre=heroe,desc=personaje,img=link)
			#heroeModel.save()
	
		template_name='marvel/home.html'



		context={
			'personaje':personaje,
			'heroe':heroe,
			'link':link,
			'historial':historial
		}
		return render(request,template_name,context)

class Historial(View):
	def get(self, request):
		template_name='marvel/historial.html'
		
		historial = Heroe.objects.all()
		return render(request,template_name,{'historial':historial})
		

main/templates/main/home.html
{%extends 'base.html'%}

{%block content%}
	<section>
		<h2>Bienvenidos Freakys</h2>
		<a href="{%url 'marv:home'%}">Busca tu personaje</a>
		<a href="{%url 'marv:historial'%}">Historial</a>
	</section>
{%endblock content%}

marvel/templates/marvel/historial.html
{%extends 'base.html'%}

{%block content%}
	{% for heroe in historial %}
		<ul class="list-inline">
			<li>{{heroe.nombre}}</li>
			<li>{{heroe.desc}}</li>
			<li><img style="max-width: 200px" src="{{heroe.img}}"></li>
		</ul>
	{%endfor%}
{%endblock content%}

marvel/templates/marvel/home.html
{%extends 'base.html'%}

{%block content%}
	<section>

		{%if personaje%}
			<img style="max-width: 200px" src="{{link}}">
			<h2>La descripcion del personaje: {{heroe}}</h2>
			<h3>{{personaje}}</h3>

			
				
		{% endif %}
		<form action="." method="post">
			<label>
				Escribe el nombre de tu super favorito:
				<input type="text" name="heroe">
				<select name="heroe">
					<option value="">selecciona un personaje</option>
					{% for heroe in historial %}
						<option value="{{heroe.nombre}}">{{heroe.nombre}}</option>
					{%endfor%}
				</select>
				<input type="submit" value="Pedir">
			</label>
			{%csrf_token%}
		</form>
	</section>
{%endblock content%}

templates/base.html
<!DOCTYPE html>
<html>
<head>
	<title>MarvelComics</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width">
	<style type="text/css">
		@keyframes palpitar{
			0%{
				transform: scale(1) rotate(0deg);
			}
			30%{
				transform: scale(0.5) rotate(45deg);
			}
			50%{
				transform: scale(0.5) rotate(170deg);
			}
			50%{
				transform: scale(1) rotate(0deg);
			}
		}

		nav{
			width: 100%;
			height: 64px;
			background: black;
			color: white;
		}
		nav span{
			font-size: 3rem;
			margin-top: 10px;
			transition: all 1s ease-in;
		}
		nav span:hover{
			color: yellow;
			font-size: 4rem;
		}
		section{
			width: 80%;

		}
		img{
			animation: palpitar 1s ease-in infinite;
		}
	</style>
</head>
<body>
	<nav>
		<span>Marvel Comics</span>
	</nav>
	{%block content%}

	{%endblock content%}
</body>
</html>